### ISSUE TITLE
Agent Specified Environment checkbox wont save in Foreman 1.11.4/1.12.1

### ISSUE THREAD

**Issue by alejandrocfg** [joshuabaird/foreman_noenv#8]
I upgraded to Foreman 1.11.4 and for some reason when I enable Agent Specified Environment in the host properties and submit the change is not saved. Any idea what could be causing this? The plugin version installed is 0.0.5. I also checked that I had :noenv_enable: true in my settings.yml.

**Comment by joshuabaird** [comment]
I was able to reproduce this in 1.12.1 as well.  I'm guessing it broke somewhere in the 1.11 series, but I'll need to dig a bit deeper.  I had some hosts that already had 'Agent Specified Environment' checked before the upgrade, and those seem to have stuck.  I'll try to find some time in the next day or so to look at this, but feel free to submit a PR if you find the problem before I do.

**Comment by domcleal** [comment]
This is probably protected/strong attributes, it filters un-whitelisted attributes out.  Try changing the `included` block in host_managed_extentions.rb:

<pre>
    included do
      alias_method_chain :info, :env
      attr_accessible :noenv
    end
</pre>

In 1.13, this changes to an item in the plugin registration (engine.rb):

```
parameter_filter Host::Managed, :noenv
```

(http://projects.theforeman.org/projects/foreman/wiki/Strong_parameters)

**Comment by alejandrocfg** [comment]
Just tested it, worked perfect. Thanks @domcleal :)

**Comment by joshuabaird** [comment]
Thanks @domcleal!  I'll cut a new release this morning to get this fixed.

**Comment by joshuabaird** [comment]
Fixed in 0.0.6 per #12!
