### ISSUE TITLE
Changes required for Foreman 1.13

### ISSUE THREAD

**Issue by joshuabaird** [joshuabaird/foreman_noenv#9]
For background information, see #8.
- Remove `attr_accessible` line from `host_managed_extension.rb`
- Add `parameter_filter Host::Managed, :noenv` to `engine.rb`

**Comment by domcleal** [comment]
I forgot that the compatibility layer in 1.13 for this change should ensure the older (1.11/12) method continues to work during 1.13 and 1.14, but will be removed in 1.15.

**Comment by joshuabaird** [comment]
It looks like 0.6 is broken in 1.13.1.  The 'host edit' form doesn't save the 'Agent Specified Environment' option.  Re-visiting this.
